version: '3.9'

services:

  db:
    image: 'db:latest'
    container_name: db
    command:
      - "-c"
      - "max_connections=200"
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345

