auth:
  token: t.m1cjaUO-4owZHxezRQONWbPz39NH-QKyjr4G8GrFvxZDBJKa8KxJwr2decgxqBwp0JymvYCojXhtNFN-PoBkOg
  account: 2091021267

telegram:
  token: 5056638065:AAECM3eJIcUFWPuf-egwc7cpTrv6D_0SGJM
  chat-id: -1001634359844

sandbox:
  account: d70c4172-7186-40ee-8cbf-150490236569

spring:
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    username: postgres
    password: 12345
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/piapi
  liquibase:
    enabled: true
    change-log: classpath:changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /system
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readinessstate:
      enabled: true
    livenessstate:
      enabled: true

grpc:
  url: invest-public-api.tinkoff.ru
  port: 443
